# Generated by Django 3.1.6 on 2021-02-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210216_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название напитка ', max_length=100, verbose_name='Название напитка')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={},
        ),
    ]
