# Generated by Django 3.1.6 on 2021-06-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210520_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(to='shop.Category', verbose_name='категория'),
        ),
    ]
